// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xymmgyluhijzlnumrwym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bW1neWx1aGlqemxudW1yd3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTY0NjQsImV4cCI6MjA2NDk3MjQ2NH0.j1eox-h2HCwIYwCND3GNmnHcoemTr4vn2BoKaXom2pI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);